# Generated by Django 5.0 on 2023-12-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=10)),
                ('admin_email', models.CharField(max_length=10)),
                ('admin_password', models.CharField(max_length=10)),
            ],
        ),
    ]
