# Generated by Django 5.0 on 2023-12-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperation_name', models.CharField(max_length=10)),
                ('cooperation_email', models.CharField(max_length=10)),
                ('cooperation_contact', models.CharField(max_length=10)),
                ('cooperation_address', models.CharField(max_length=10)),
                ('cooperation_password', models.CharField(max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
