# Generated by Django 5.0 on 2023-12-31 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_cooperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_name', models.CharField(max_length=10)),
                ('health_email', models.CharField(max_length=10)),
                ('health_contact', models.CharField(max_length=10)),
                ('health_address', models.CharField(max_length=10)),
                ('health_password', models.CharField(max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
