# Generated by Django 5.0 on 2024-01-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_rename_tbl_cooperation_tbl_corporation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10)),
                ('shop_status', models.IntegerField(default=0)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_street')),
            ],
        ),
    ]
