# Generated by Django 5.0 on 2024-01-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0002_tbl_shopregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=10)),
                ('food_rate', models.CharField(max_length=10)),
                ('food_description', models.CharField(max_length=10)),
                ('food_photo', models.FileField(upload_to='UserDocs/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration')),
            ],
        ),
    ]
