# Generated by Django 5.0 on 2024-01-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
        ('User', '0003_remove_tbl_complaint_shop_remove_tbl_rating_food_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_food',
        ),
    ]
