# Generated by Django 5.0 on 2024-01-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
