# Generated by Django 5.0 on 2024-01-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_delete_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=10)),
                ('slot_id', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
            ],
        ),
    ]
