# Generated by Django 5.0 on 2024-01-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_slot'),
        ('Guest', '0004_tbl_shopregistration'),
        ('Shop', '0007_delete_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_slot')),
            ],
        ),
    ]
