# Generated by Django 5.0 on 2024-02-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_shopregistration_shop_liscencedate'),
        ('Shop', '0008_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(auto_now_add=True)),
                ('renewal_status', models.IntegerField(default=0)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration')),
            ],
        ),
    ]
