# Generated by Django 5.0.2 on 2024-02-24 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_shopregistration_shop_liscencedate'),
        ('Shop', '0009_tbl_renewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_count', models.CharField(max_length=10)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration')),
            ],
        ),
    ]
