# Generated by Django 5.0 on 2024-01-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_rename_tbl_cooperation_tbl_corporation_and_more'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shopregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=10)),
                ('shop_liscence', models.CharField(max_length=15, null=True)),
                ('shop_contact', models.CharField(max_length=10)),
                ('shop_email', models.CharField(max_length=10)),
                ('shop_address', models.CharField(max_length=10)),
                ('shop_photo', models.FileField(upload_to='UserDocs/')),
                ('owner_name', models.CharField(max_length=10)),
                ('owner_photo', models.FileField(upload_to='UserDocs/')),
                ('owner_proof', models.FileField(upload_to='UserDocs/')),
                ('shop_password', models.CharField(max_length=10)),
                ('shop_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_street')),
            ],
        ),
    ]
