# Generated by Django 5.0 on 2024-02-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_shopregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_shopregistration',
            name='shop_liscencedate',
            field=models.DateField(null=True),
        ),
    ]
