# Generated by Django 5.0 on 2024-01-05 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_shopregistration'),
        ('Shop', '0003_initial'),
        ('User', '0003_remove_tbl_complaint_shop_remove_tbl_rating_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quantity', models.CharField(max_length=10)),
                ('cart_status', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_food')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=10)),
                ('complaint_description', models.CharField(max_length=10)),
                ('complaint_reply', models.CharField(max_length=10)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.CharField(max_length=10)),
                ('user_review', models.CharField(max_length=10)),
                ('review_date', models.CharField(max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
