# Generated by Django 5.0 on 2024-01-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_cart_tbl_complaint_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
