# Generated by Django 5.0.2 on 2024-02-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_shopregistration_shop_liscencedate'),
        ('User', '0007_remove_tbl_cart_booking_remove_tbl_cart_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=10)),
                ('booking_time', models.CharField(max_length=10)),
                ('booking_count', models.CharField(max_length=10)),
                ('booking_amount', models.CharField(max_length=10)),
                ('booking_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
