# Generated by Django 5.0.2 on 2024-02-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
