# Generated by Django 5.0.2 on 2024-02-25 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_shopregistration_shop_liscencedate'),
        ('User', '0010_tbl_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration'),
        ),
    ]
